### ISSUE TITLE
A problem

### ISSUE THREAD

**Issue by jlx15588** [tsinghua-fib-lab/SIGIR24-FRec#1]
When I ran the command : `python run.py --model model --name trial`, I encountered the following question: 
```
Traceback (most recent call last):
  File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
    return fn(*args)
  File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
	 [[{{node sequential/GatherV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 273, in <module>
    app.run(main)
  File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 262, in main
    model = model.fit(train_file, valid_file, valid_num_ngs=flags_obj.valid_num_ngs) 
  File "/mnt/mydisk7/jgx/frec-sigir24/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 150, in fit
    step_result = self.train(train_sess, batch_data_input)
  File "/mnt/mydisk7/x/frec-sigir24/recommenders/models/deeprec/models/base_model.py", line 411, in train
    feed_dict=feed_dict,
  File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
    run_metadata_ptr)
  File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
    run_metadata)
  File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
	 [[node sequential/GatherV2 (defined at /mydisk7/lx/frec-sigir24/recommenders/models/deeprec/models/sequential/model.py:47) ]]
```
Can you help me solve the problem? 
thank you!

**Comment by wjjln** [comment]
I have tested the code, and it runs successfully.
Please make sure that your Tensorflow version is 2.1.0 (Python 3.6.10, although I don't think this is necessary, since the error is from 'sess.run(to_run, feed_dict=feed_dict)' ).

**Comment by wjjln** [comment]
> When I ran the command : `python run.py --model model --name trial`, I encountered the following question:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
>     return fn(*args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
>     target_list, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[{{node sequential/GatherV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 273, in <module>
>     app.run(main)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 262, in main
>     model = model.fit(train_file, valid_file, valid_num_ngs=flags_obj.valid_num_ngs) 
>   File "/mnt/mydisk7/jgx/frec-sigir24/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 150, in fit
>     step_result = self.train(train_sess, batch_data_input)
>   File "/mnt/mydisk7/x/frec-sigir24/recommenders/models/deeprec/models/base_model.py", line 411, in train
>     feed_dict=feed_dict,
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
>     run_metadata_ptr)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
>     run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[node sequential/GatherV2 (defined at /mydisk7/lx/frec-sigir24/recommenders/models/deeprec/models/sequential/model.py:47) ]]
> ```
> 
> Can you help me solve the problem? thank you!

I have tested the code, and it runs successfully.
Please make sure that your Tensorflow version is 2.1.0 (Python 3.6.10, although I don't think this is necessary, since the error is from *sess.run(to_run, feed_dict=feed_dict)* ).

**Comment by Ezra521** [comment]
Original stack trace for 'sequential/GatherV2_1':
  File "run.py", line 275, in <module>
    app.run(main)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "run.py", line 247, in main
    model, model_path, _ = get_model(flags_obj, exp_name)
  File "run.py", line 218, in get_model
    model = Model(hparams, input_creator, seed=None)
  File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 54, in __init__
    super().__init__(hparams, iterator_creator, graph=self.graph, seed=seed)
  File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/base_model.py", line 59, in __init__
    self.logit, self.fatigue_logit, self.fatigue_logit_fatigue = self._build_graph()
  File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 75, in _build_graph
    interest_output_rec, fatigue_logit, interest_output_fatigue, fatigue_logit_fatigue = self._build_seq_graph()
  File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 40, in _build_seq_graph
    interest_output_fatigue, fatigue_output_fatigue = self._basic_build_graph(self.users_fatigue_embedding, fatigue_history_emb, self.target_item_fatigue_embedding, self.iterator.fatigue_mask, self.iterator.CL_fatigue_mask, self.iterator.recent_fatigue_idx)
  File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 53, in _basic_build_graph
    recent_item_emb = tf.gather(history_emb, recent_idx, axis=1, batch_dims=1)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4125, in gather_v2
    batch_dims=batch_dims)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4102, in gather
    params, indices, axis, batch_dims=batch_dims, name=name)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3690, in gather_v2
    batch_dims=batch_dims, name=name)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by Ezra521** [comment]
> Original stack trace for 'sequential/GatherV2_1': File "run.py", line 275, in app.run(main) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 308, in run _run_main(main, args) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main sys.exit(main(argv)) File "run.py", line 247, in main model, model_path, _ = get_model(flags_obj, exp_name) File "run.py", line 218, in get_model model = Model(hparams, input_creator, seed=None) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 54, in **init** super().**init**(hparams, iterator_creator, graph=self.graph, seed=seed) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/base_model.py", line 59, in **init** self.logit, self.fatigue_logit, self.fatigue_logit_fatigue = self._build_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 75, in _build_graph interest_output_rec, fatigue_logit, interest_output_fatigue, fatigue_logit_fatigue = self._build_seq_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 40, in _build_seq_graph interest_output_fatigue, fatigue_output_fatigue = self._basic_build_graph(self.users_fatigue_embedding, fatigue_history_emb, self.target_item_fatigue_embedding, self.iterator.fatigue_mask, self.iterator.CL_fatigue_mask, self.iterator.recent_fatigue_idx) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 53, in _basic_build_graph recent_item_emb = tf.gather(history_emb, recent_idx, axis=1, batch_dims=1) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4125, in gather_v2 batch_dims=batch_dims) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4102, in gather params, indices, axis, batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3690, in gather_v2 batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper attrs=attr_protos, op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in **init** self._traceback = tf_stack.extract_stack()

i have the same error

**Comment by Felis-3** [comment]
> _sess.run(to_run, feed_dict=feed_dict)_ ).

I have the same problem.I try clsr and slirec, it runs successfully. But python run.py --model model --name trial, it's not.

**Comment by Felis-3** [comment]
> When I ran the command : `python run.py --model model --name trial`, I encountered the following question:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
>     return fn(*args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
>     target_list, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[{{node sequential/GatherV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 273, in <module>
>     app.run(main)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 262, in main
>     model = model.fit(train_file, valid_file, valid_num_ngs=flags_obj.valid_num_ngs) 
>   File "/mnt/mydisk7/jgx/frec-sigir24/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 150, in fit
>     step_result = self.train(train_sess, batch_data_input)
>   File "/mnt/mydisk7/x/frec-sigir24/recommenders/models/deeprec/models/base_model.py", line 411, in train
>     feed_dict=feed_dict,
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
>     run_metadata_ptr)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
>     run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[node sequential/GatherV2 (defined at /mydisk7/lx/frec-sigir24/recommenders/models/deeprec/models/sequential/model.py:47) ]]
> ```
> 
> Can you help me solve the problem? thank you!

I have the same problem.I try clsr and slirec, it runs successfully. But python run.py --model model --name trial, it's not.

**Comment by invictuszhao** [comment]
> > Original stack trace for 'sequential/GatherV2_1': File "run.py", line 275, in app.run(main) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 308, in run _run_main(main, args) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main sys.exit(main(argv)) File "run.py", line 247, in main model, model_path, _ = get_model(flags_obj, exp_name) File "run.py", line 218, in get_model model = Model(hparams, input_creator, seed=None) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 54, in **init** super().**init**(hparams, iterator_creator, graph=self.graph, seed=seed) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/base_model.py", line 59, in **init** self.logit, self.fatigue_logit, self.fatigue_logit_fatigue = self._build_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 75, in _build_graph interest_output_rec, fatigue_logit, interest_output_fatigue, fatigue_logit_fatigue = self._build_seq_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 40, in _build_seq_graph interest_output_fatigue, fatigue_output_fatigue = self._basic_build_graph(self.users_fatigue_embedding, fatigue_history_emb, self.target_item_fatigue_embedding, self.iterator.fatigue_mask, self.iterator.CL_fatigue_mask, self.iterator.recent_fatigue_idx) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 53, in _basic_build_graph recent_item_emb = tf.gather(history_emb, recent_idx, axis=1, batch_dims=1) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4125, in gather_v2 batch_dims=batch_dims) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4102, in gather params, indices, axis, batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3690, in gather_v2 batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper attrs=attr_protos, op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in **init** self._traceback = tf_stack.extract_stack()
> 
> i have the same error
i have the same error, too

**Comment by Flower734** [comment]
Can I ask how u Configure your enviroment？I find the author update a requirement.txt file,but it has hundred package,and I couldn't get all the right versions and i couldn't run it successfully, so i was wondering how did u get your enviroment configured？

**Comment by Flower734** [comment]
> > > Original stack trace for 'sequential/GatherV2_1': File "run.py", line 275, in app.run(main) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 308, in run _run_main(main, args) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/absl/app.py", line 254, in _run_main sys.exit(main(argv)) File "run.py", line 247, in main model, model_path, _ = get_model(flags_obj, exp_name) File "run.py", line 218, in get_model model = Model(hparams, input_creator, seed=None) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 54, in **init** super().**init**(hparams, iterator_creator, graph=self.graph, seed=seed) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/base_model.py", line 59, in **init** self.logit, self.fatigue_logit, self.fatigue_logit_fatigue = self._build_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 75, in _build_graph interest_output_rec, fatigue_logit, interest_output_fatigue, fatigue_logit_fatigue = self._build_seq_graph() File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 40, in _build_seq_graph interest_output_fatigue, fatigue_output_fatigue = self._basic_build_graph(self.users_fatigue_embedding, fatigue_history_emb, self.target_item_fatigue_embedding, self.iterator.fatigue_mask, self.iterator.CL_fatigue_mask, self.iterator.recent_fatigue_idx) File "/data0/data1/qiankun/SIGIR24-FRec/recommenders/models/deeprec/models/sequential/model.py", line 53, in _basic_build_graph recent_item_emb = tf.gather(history_emb, recent_idx, axis=1, batch_dims=1) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4125, in gather_v2 batch_dims=batch_dims) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper return target(*args, **kwargs) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 4102, in gather params, indices, axis, batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 3690, in gather_v2 batch_dims=batch_dims, name=name) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 742, in _apply_op_helper attrs=attr_protos, op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3322, in _create_op_internal op_def=op_def) File "/data1/qiankun/miniconda3/envs/frec36/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1756, in **init** self._traceback = tf_stack.extract_stack()
> > 
> > 
> > i have the same error
> > i have the same error, too

i have the same

> When I ran the command : `python run.py --model model --name trial`, I encountered the following question:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
>     return fn(*args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
>     target_list, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[{{node sequential/GatherV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 273, in <module>
>     app.run(main)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 262, in main
>     model = model.fit(train_file, valid_file, valid_num_ngs=flags_obj.valid_num_ngs) 
>   File "/mnt/mydisk7/jgx/frec-sigir24/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 150, in fit
>     step_result = self.train(train_sess, batch_data_input)
>   File "/mnt/mydisk7/x/frec-sigir24/recommenders/models/deeprec/models/base_model.py", line 411, in train
>     feed_dict=feed_dict,
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
>     run_metadata_ptr)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
>     run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[node sequential/GatherV2 (defined at /mydisk7/lx/frec-sigir24/recommenders/models/deeprec/models/sequential/model.py:47) ]]
> ```
> 
> Can you help me solve the problem? thank you!

I have the same error

**Comment by Flower734** [comment]
> When I ran the command : `python run.py --model model --name trial`, I encountered the following question:
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1367, in _do_call
>     return fn(*args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1352, in _run_fn
>     target_list, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1445, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[{{node sequential/GatherV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 273, in <module>
>     app.run(main)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/mnt/mydisk4/anaconda3/envs/_tf2/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/mnt/mydisk7/lx/frec-sigir24/run.py", line 262, in main
>     model = model.fit(train_file, valid_file, valid_num_ngs=flags_obj.valid_num_ngs) 
>   File "/mnt/mydisk7/jgx/frec-sigir24/recommenders/models/deeprec/models/sequential/sequential_base_model.py", line 150, in fit
>     step_result = self.train(train_sess, batch_data_input)
>   File "/mnt/mydisk7/x/frec-sigir24/recommenders/models/deeprec/models/base_model.py", line 411, in train
>     feed_dict=feed_dict,
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 960, in run
>     run_metadata_ptr)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1183, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1361, in _do_run
>     run_metadata)
>   File "/mnt/mydisk4/anaconda3/envs/lx_tf2/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1386, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2415,37] = -1 is not in [0, 100)
> 	 [[node sequential/GatherV2 (defined at /mydisk7/lx/frec-sigir24/recommenders/models/deeprec/models/sequential/model.py:47) ]]
> ```
> 
> Can you help me solve the problem? thank you!

I have the same error
